<?php



/**
 * Skeleton subclass for representing a row from the 'sf_plop_slot_config_i18n' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Thu Feb  3 13:02:26 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopPlugin.lib.model
 */
class sfPlopSlotConfigI18n extends BasesfPlopSlotConfigI18n {

  public function getCulture()
  {
    return $this->getLocale();
  }
} // sfPlopSlotConfigI18n
