<?php



/**
 * Skeleton subclass for representing a row from the 'sf_plop_page' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Fri Jan 28 18:11:39 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopPlugin.lib.model
 */
class sfPlopPage extends BasesfPlopPage {

  protected $isTemplate = null;
  protected $isTemplateChild = null;

  /**
   * If the object is displayed, the slug is sent.
   * @return Boolean
   */
  public function __toString()
  {
    return $this->getSlug();
  }

  /**
   * Shortcut function to get the is_category column of the page.
   * @return Boolean
   */
  public function isCategory()
  {
    return $this->getIsCategory();
  }

  /**
   * Shortcut function to get the publication status of the page.
   * @return Boolean
   */
  public function isPublished()
  {
    return $this->getIsPublished();
  }

  /**
   * Override the default method retrieving the [title] column value.
   *
   * @return string
   */
  public function getTitle()
  {
    $t = parent::getTitle();
    if (is_null($t))
    {
      if ($this->getCulture() == sfPlop::get('sf_plop_default_culture'))
        $title = 'Page';
      else
        $title = $this->getTranslation(sfPlop::get('sf_plop_default_culture'))->getTitle();
      $this->setTitle($title);
      $this->save();
    }

    return parent::getTitle();
  }

  /**
   * Check if the page has slots in his page.
   * @return Boolean
   */
  public function hasSlots()
  {
    return $this->isTemplate()
      ? ($this->countsfPlopSlots() > 0 ? true : false)
      : ($this->countsfPlopSlotConfigs() > 0 ? true : false)
    ;
  }

  /**
   * Check if the current page has a slot area
   * @return Boolean
   */
  public function hasSlotArea()
  {
    $count = sfPlopSlotQuery::create()
//      ->filterByPageId($this->isTemplate() ? $this->getId() : $this->getTemplateId())
      ->filterByPageId($this->getId())
      ->filterByTemplate('Area')
      ->groupById()
      ->count();

    return $count ? true : false;
  }

  /**
   * Checkif the page has pages using this one as a template.
   * @return Boolean
   */
  public function hasTemplateChildren()
  {
    return $this->countTemplateChildren() > 0 ? true : false;
  }

  /**
   * Count the number of page using this one as a template.
   * @return Boolean
   */
  public function countTemplateChildren()
  {
    return sfPlopPageQuery::create()
      ->filterByTemplateId($this->getId())
      ->count()
    ;
  }

  /**
   * Check if the page is a template.
   * @return Boolean
   */
  public function isTemplate()
  {
    if ($this->isTemplate === NULL)
      $this->isTemplate =
        ($this->countTemplateChildren() >= 0 && is_null($this->getTemplateId()))
        ? true : false;

    return $this->isTemplate;
  }

  /**
   * Check if the page is a template child.
   * @return Boolean
   */
  public function isTemplateChild()
  {
    if ($this->isTemplateChild === NULL)
      $this->isTemplateChild =
        (!is_null($this->getTemplateId()) && $this->getParent()->isTemplate())
        ? true : false;

    return $this->isTemplateChild;
  }

  /**
   * Get the template page.
   * @return Boolean
   */
  public function getTemplate($culture = null)
  {
    return $culture
      ? sfPlopPageQuery::create()
        ->joinWithI18n($this->culture)
        ->findOneById($this->getTemplateId())
      : sfPlopPagePeer::retrieveByPK($this->getTemplateId())
    ;
  }

  /**
   * Copy the slots from another page
   * @param sfPlopPage $page_ref
   */
  public function copySlotsFrom(sfPlopPage $page_ref)
  {
    foreach ($page_ref->getsfPlopSlots() as $slot_ref)
    {
      $slot = new sfPlopSlot();
      $slot_ref->copyInto($slot, true);
      $slot->swapPage($this->getId());
    }
  }

  /**
   * Override the doSave function to do some custom tweaks.
   * @param PropelPDO $con
   */
  protected function doSave(PropelPDO $con)
  {
    if ($this->isColumnModified(sfPlopPagePeer::TEMPLATE_ID))
    {
      $tpl = sfPlopPagePeer::retrieveByPK($this->getTemplateId());
      if ($tpl && $tpl->getTemplateId())
      {
        $tplTpl = sfPlopPagePeer::retrieveByPK($tpl->getTemplateId());
        if ($tplTpl && $tplTpl->hasSlotArea())
          $this->setTemplateId($tpl->getId());
      }
      elseif (!$tpl)
      {
        $this->setTemplateId(null);
      }
    }

    return parent::doSave($con);
  }

} // sfPlopPage
